**Import requirements**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import re
import pandas as pd
import math

Input text

In [3]:
#file=open("/content/drive/MyDrive/Coding/Cryptography/input.txt","r")
file=open("/content/drive/MyDrive/Semester - 7/Crypto/chroniclesofnarnia.txt","r")

In [4]:
input_string = file.read()

**Pre-processing - removing special characters and spaces**

In [81]:
def preprocess(plaintext):
  #remove_space = re.sub('^A-za-z0-9+',"",plaintext)
  test_str = ''.join(letter for letter in input_string if letter.isalnum())
  to_lower = test_str.lower()
  return to_lower

plaintext=preprocess(input_string)

In [82]:
plaintext

'thelionthewitchandthewardrobebycslewischapteronelucylooksintoawardrobeoncetherewerefourchildrenwhosenameswerepetersusanedmundandlucythisstoryisaboutsomethingthathappenedtothemwhentheyweresentawayfromlondonduringthewarbecauseoftheairraidstheyweresenttothehouseofanoldprofessorwholivedintheheartofthecountrytenmilesfromthenearestrailwaystationandtwomilesfromthenearestpostofficehehadnowifeandhelivedinaverylargehousewithahousekeepercalledmrsmacreadyandthreeservantstheirnameswereivymargaretandbettybuttheydonotcomeintothestorymuchhehimselfwasaveryoldmanwithshaggywhitehairwhichgrewovermostofhisfaceaswellasonhisheadandtheylikedhimalmostatoncebutonthefirsteveningwhenhecameouttomeetthematthefrontdoorhewassooddlookingthatlucywhowastheyoungestwasalittleafraidofhimandedmundwhowasthenextyoungestwantedtolaughandhadtokeeponpretendinghewasblowinghisnosetohideitassoonastheyhadsaidgoodnighttotheprofessorandgoneupstairsonthefirstnighttheboyscameintothegirlsroomandtheyalltalkeditoverwevefallenonourfeetandno

**Creating a dictionary for accepted characters**

In [7]:
my_dict = {0:'a', 1:'b', 2:'c', 3:'d', 4:'e', 5:'f', 6:'g', 7:'h', 8:'i', 9:'j', 10:'k', 11:'l', 12:'m', 13:'n', 14:'o', 15:'p', 16:'q', 17:'r', 18:'s', 19:'t', 20:'u', 21:'v', 22:'w', 23:'x', 24:'y', 25:'z',26:'0',27:'1',28:'2',29:'3',30:'4',31:'5',32:'6',33:'7',34:'8',35:'9'} 

**Generating Cipher Text**

In [83]:
def generateKey(string, key):
    key = list(key)
    if len(string) == len(key):
        return(key)
    else:
        for i in range(len(string) -
                       len(key)):
            key.append(key[i % len(key)])
    return("" . join(key))
     
def cipherText(string, key):
    cipher_text = []
    for i in range(len(string)):
        x = (ord(string[i]) +
             ord(key[i])) % 26
        x += ord('A')
        cipher_text.append(chr(x))
    return("" . join(cipher_text))

string = plaintext
keyword1 = "thechroniclesofnarnia"
keyword2 = "orderofthephoenix"
key1 = generateKey(string, keyword1)
key2 = generateKey(string, keyword2)
cipher_text_correct = cipherText(string,key1)   
cipher_text_incorrect = cipherText(string,key2)    


**Converting the cipher text and plain text  to ascii then to 8-bit binary value**

In [84]:
def convertion(text):
  ascii_value =[]
  binary_str=[]
  
  for i in range(len(text)):
    ascii_value.append(ord(text[i]))
  
  for i in range(len(ascii_value)):
    binary_value = bin(ascii_value[i])[2:]
    while len(binary_value) < 8:
      binary_value += '0'
      bnr = binary_value[::-1]
      binary_str.append(bnr)
  return binary_str

binary_ciphertext_1=convertion(cipher_text_correct)
binary_ciphertext_2=convertion(cipher_text_incorrect)
binary_plaintext=convertion(plaintext)

**Spliting each bit of the binary number**

In [85]:
def spliting_values(text):
  row = []
  for i in range(len(text)):
    if len(text[i]) < 8:
      pass
    else:
      for j in range(0,8):
        row.append(text[i][j])
  return row

cipher_row_1 = spliting_values(binary_ciphertext_1)
cipher_row_2 = spliting_values(binary_ciphertext_2)
plain_row = spliting_values(binary_plaintext)

**Creating DataFrame**

In [86]:
df=pd.DataFrame([], columns =list(range(1,66)))

In [87]:
loop=math.ceil(len(cipher_row_1) / 32)
m=0
n=32
label1=[1]
label0=[0]
for i in range(loop):
  a = plain_row[m:n] + cipher_row_1[m:n]+label1
  b = plain_row[m:n] + cipher_row_2[m:n]+label0
  if len(a) < 64:
    pass
  else:
    df.loc[len(df)] = a
    df.loc[len(df)] = b
  m+=32
  n +=32

**Label = 1 for shift cipher** <br>
**Label = 0 for random cipher**

In [88]:
df

1  2  3  4  5  6  7  8  9  10  ... 56 57 58 59 60 61 62 63 64 65
0      0  0  0  1  0  1  1  1  0  0  ...  1  0  0  1  0  1  1  0  1  1
1      0  0  0  1  0  1  1  1  0  0  ...  1  0  0  1  0  0  0  0  1  0
2      0  1  0  0  1  0  1  1  0  1  ...  1  0  1  1  0  0  1  0  1  1
3      0  1  0  0  1  0  1  1  0  1  ...  1  0  1  0  0  1  1  0  1  0
4      0  0  0  0  1  0  1  1  0  1  ...  1  0  1  0  0  1  1  0  1  1
...   .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
26387  0  0  1  1  0  0  1  1  0  1  ...  1  0  0  1  0  1  0  0  1  0
26388  0  1  1  0  0  0  1  1  0  1  ...  1  0  1  1  0  0  0  0  1  1
26389  0  1  1  0  0  0  1  1  0  1  ...  1  0  0  1  1  0  1  0  1  0
26390  0  0  0  0  1  0  1  1  0  1  ...  1  0  1  1  0  0  0  0  1  1
26391  0  0  0  0  1  0  1  1  0  1  ...  1  0  0  1  0  1  1  0  1  0

[26392 rows x 65 columns]

Building Machine Learning Model for classfication of 1 and 0

In [89]:
# Putting feature variable to X
X = df.drop(65,axis=1)
# Putting response variable to y
y = df[65]

In [90]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [91]:
# now lets split the data into train and test
from sklearn.model_selection import train_test_split

In [92]:
# Splitting the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42)
X_train.shape, X_test.shape

((18474, 64), (7918, 64))

In [93]:
import tensorflow as tf

In [94]:
X_train=np.asarray(X_train).astype(np.int)

y_train=np.asarray(y_train).astype(np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the releas

In [26]:
#Initialising ANN
ann = tf.keras.models.Sequential()
#Adding First Hidden Layer
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
#Adding Second Hidden Layer
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
#Adding Output Layer
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))
#Compiling ANN
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])
#Fitting ANN
ann.fit(X_train,y_train,batch_size=32,epochs = 100)
#Fitting ANN
ann.fit(X_train,y_train,batch_size=32,epochs = 100)

Epoch 1/100
578/578 [==============================] - 2s 2ms/step - loss: 0.6936 - accuracy: 0.5027
Epoch 2/100
578/578 [==============================] - 1s 2ms/step - loss: 0.6922 - accuracy: 0.5205
Epoch 3/100
578/578 [==============================] - 1s 2ms/step - loss: 0.6893 - accuracy: 0.5377
Epoch 4/100
578/578 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5486
Epoch 5/100
578/578 [==============================] - 1s 2ms/step - loss: 0.6786 - accuracy: 0.5669
Epoch 6/100
578/578 [==============================] - 1s 2ms/step - loss: 0.6723 - accuracy: 0.5815
Epoch 7/100
578/578 [==============================] - 1s 2ms/step - loss: 0.6671 - accuracy: 0.5906
Epoch 8/100
578/578 [==============================] - 1s 2ms/step - loss: 0.6635 - accuracy: 0.5995
Epoch 9/100
578/578 [==============================] - 1s 2ms/step - loss: 0.6596 - accuracy: 0.6046
Epoch 10/100
578/578 [==============================] - 1s 2ms/step - loss: 0.6559 - accura

In [95]:
X_test=np.asarray(X_test).astype(np.int)
y_test=np.asarray(y_test).astype(np.int)
y_pred = ann.predict(X_test)

 41/248 [===>..........................] - ETA: 0s

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the releas

248/248 [==============================] - 0s 1ms/step


In [55]:
y_pred

array([[0.1874726 ],
       [0.9582425 ],
       [0.7895163 ],
       ...,
       [0.45016274],
       [0.34511152],
       [0.10914662]], dtype=float32)

In [56]:
y_test

array([0, 1, 1, ..., 0, 1, 0])

In [57]:
y_pred = (y_pred > 0.5)

In [58]:
y_pred

array([[False],
       [ True],
       [ True],
       ...,
       [False],
       [False],
       [False]])

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[3436  521]
 [1228 2733]]


0.7791108865875221

##Gradient Boosting

In [96]:
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import r2_score
from sklearn import model_selection
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report




In [78]:
kf = KFold(n_splits=25,random_state=42,shuffle=True)
for train_index,val_index in kf.split(X):
    X_train,X_val = X.iloc[train_index],X.iloc[val_index],
    y_train,y_val = Y.iloc[train_index],Y.iloc[val_index],

In [97]:
gradient_booster = GradientBoostingClassifier(learning_rate=0.01)
gradient_booster.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.01,
 'loss': 'deviance',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [101]:
kf = KFold(n_splits=25,random_state=42,shuffle=True)
for train_index,val_index in kf.split(X):
    X_train,X_val = X.iloc[train_index],X.iloc[val_index],
    y_train,y_val = Y.iloc[train_index],Y.iloc[val_index],

In [102]:
gradient_booster.fit(X_train,y_train)
print(classification_report(y_val,gradient_booster.predict(X_val)))

              precision    recall  f1-score   support

           0       0.62      0.68      0.65       519
           1       0.66      0.59      0.62       536

    accuracy                           0.63      1055
   macro avg       0.64      0.63      0.63      1055
weighted avg       0.64      0.63      0.63      1055

